---
title: "visualization-uhuru-day2.Rmd"
author: "Austin Mercado"
date: "2023-02-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
ACACIA <- read.csv(file = "../data-raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t", na.strings = "dead")
```

######
In Class Activity Day:2
######

```{r}
ggplot(data = ACACIA, mapping = aes(x = CIRC, y = HEIGHT)) +
geom_point(size = 3, color = "blue", alpha = 0.5) +
scale_y_log10() +
scale_x_log10()
```

```{r}
ggplot(ACACIA, aes(x = CIRC, y = HEIGHT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth()
```

```{r}
ggplot(ACACIA, aes(x = CIRC, y = HEIGHT, color = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth()
```

```{r}
ggplot(ACACIA, aes(x = CIRC, y = HEIGHT, color = TREATMENT, linetype = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth()
```

```{r}
ggplot(ACACIA, aes(x = CIRC, y = HEIGHT, color = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth(method = "lm") # try with "glm"
```

```{r}
ggplot(data = ACACIA, mapping = aes(x = TREATMENT)) +
geom_bar()
```

```{r}
ggplot(ACACIA, aes(x = CIRC)) +
geom_histogram(fill = "red")
```

```{r}
ggplot(ACACIA, aes(x = CIRC)) +
geom_histogram(fill = "red")
```

```{r}
ggplot(ACACIA, aes(x = CIRC, fill = TREATMENT)) +
geom_histogram(bins = 20, color = "gray")
```

```{r}
ggplot() +
geom_point(data = ACACIA,
           mapping = aes(x = CIRC, y = HEIGHT,
                         color = TREATMENT)) +
geom_smooth(data = ACACIA,
            mapping = aes(x = CIRC, y = HEIGHT))
```

```{r}
ggplot() +
geom_point(data = ACACIA,
           mapping = aes(x = CIRC, y = HEIGHT,
                         color = TREATMENT)) +
geom_smooth(data = ACACIA,
            mapping = aes(x = CIRC, y = HEIGHT)) +
geom_histogram(data = ACACIA,
               mapping = aes(x = CIRC, color = TREATMENT),
               alpha = 0.1)
```

```{r}
ggsave("acacia_by_treatment.jpg")
```

```{r}
ggsave("acacia_by_treatment.pdf", height = 5, width = 5)
```

We are working with the file 'ACACIA_DREPANOLOBIUM_SURVEY.txt' file that currently lives in the 'data-raw' folder.

```{r}
#make sure to provude file name as relative path
read.csv(file = "../data-raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t", na.strings = "dead") -> ACACIA2
```

```{r}
head(ACACIA2)
```

##Plot the data as a scatterplot

For this we use the function 'geom_point()'
```{r}
library(ggplot2)
ggplot(data = ACACIA2, mapping = aes(x = HEIGHT, y = FRUITS, color = ANT)) + geom_point(size = 3, alpha = 0.5) + facet_wrap(~ANT)
```